still nothing works.

diff --git a/partitions b/partitions
--- a/partitions
+++ b/partitions
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+error() { clear; printf "ERROR:\\n%s\\n" "$1"; exit;}
+
 # Asks user for CPU type and creates $cpu variable, to install the proper  later.
 getcpu() {
 
@@ -40,6 +42,9 @@ chooseesppart() {
 	declare -i esppartnumber
 	esppartnumber=$(dialog --title "Please select your ESP partition to be formated and mounted at /boot:" --menu "$(lsblk) " 0 0 0 $(listpartnumb) 3>&1 1>&2 2>&3 3>&1)
 	
+	# Exit the process if the user selects <cancel> instead of a partition.
+	[ $? -eq 1 ] && error "You didn't select any partition. Exiting..."
+
 	# This is the desired partition.
 	esppart=$( blkid -o list | awk '{print $1}'| grep "^/" | tr ' ' '\n' | sed -n ${esppartnumber}p)
 	
@@ -58,24 +63,26 @@ chooseesppart
 while [ $? -eq 1 ] ; do
 	chooseesppart
 done
+	#clear
+	#echo $esppart
+	#echo $cpu
 
-clear
-echo $esppart
-echo $cpu
+# Formats selected esp partition.
+mkfs.fat -n "ESP" -F32 $esppart
 
+# Mounts the selected esp partition to /mnt/boot
+mount $esppart /mnt/boot || mkdir /mnt/boot && mount $esppart /mnt/boot
 
-## Formats selected esp partition.
-#mkfs.fat -n "ESP" -F32 $esppart
+# Installs cpu's microcode if the cpu is either intel or amd.
+instmicrocode
 
-## Mounts the selected esp partition to /mnt/boot
-#mount $esppart /mnt/boot || mkdir /mnt/boot && mount $esppart /mnt/boot
+# Installs systemd-boot to the eps partition
+bootctl --path=/boot install
 
-## Installs cpu's microcode if the cpu is either intel or amd.
-#instmicrocode
+# Creates pacman hook to update systemd-boot after package upgrade.
+mkdir -p /etc/pacman.d/hooks
+curl https://raw.githubusercontent.com/ispanos/YARBS/master/files/bootctl-update.hook > /etc/pacman.d/hooks/bootctl-update.hook
 
-## Installs systemd-boot to the eps partition
-#bootctl --path=/boot install
+# Creates loader.conf. Stored in files/ folder on repo.
+curl https://raw.githubusercontent.com/ispanos/YARBS/master/files/loader.conf > /boot/loader/loader.conf
 
-## Creates pacman hook to update systemd-boot after package upgrade.
-#mkdir -p /etc/pacman.d/hooks
-#curl https://raw.githubusercontent.com/ispanos/YARBS/master/files/bootctl-update.hook > /etc/pacman.d/hooks/bootctl-update.hook
